# system setup
sudo: required
dist: trusty

# language setup
language: node_js
node_js:
    - '8'

# command to run tests

after_install:
    - npm run bootstrap

jobs:
    include:
        - stage: tests
          script: test:coverge:report
        - stage: flow
          script: npm run flow
