// flow-typed signature: b65958efeec63ef619e19c385f33eb46
// flow-typed version: <<STUB>>/quark-build_v^0.0.9-beta.26/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'quark-build'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'quark-build' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'quark-build/index' {
  declare module.exports: $Exports<'quark-build'>;
}
declare module 'quark-build/index.js' {
  declare module.exports: $Exports<'quark-build'>;
}
