// flow-typed signature: 9e81366ecb1e63e49982c781713b8afc
// flow-typed version: <<STUB>>/svgs_v3.x.x/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svgs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svgs' {
  declare module.exports: any;
}
